### PR TITLE
HTML validation fixes

### LINKED ISSUE #9: HTML valdiation errors
Hi folks,

I uncovered some problems with the site's HTML. Given your permission, I'd like to issue a PR or two to fix these:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fnztechrally.com%2F

Cheers,
-Shaun

### PR DESCRIPTION
**Pull request by ndorfin**
Fixes #9 

In this PR, I:

1. Removed the redundant `<head>` and `<body>` elements. These are inferred.
2. Some pages were missing a heading structure
   - A `<main>` element was used, but it didn't have an associated `<header>`, compounded by the above. This element was shifted up into the `base.njk` template, reducing duplications across all templates.
   - Some `<h2>`s were added.
   - The `pageHeader` block now spits out a `<header>` in the base template. All pages should have one defined, except for the homepage.
3. Most of the `<time>` elements didn't have valid `datetime` attribute values. We need ISO8601 dates in that value. Some of the `<time>` elements were nested or had incomplete `datetime` values.
4. The `<head>` elements were cleaned up, both for Schema.org reasons, but mostly for validation issues. e.g. one can't have an `itemprop` AND `property` attribute on the same element.
   - The `link rel="icon"` element was removed, since `favicon.ico` already exists in the root of the site.
   - The proprietary `X-UA-Compatible` meta element was removed, since IE support is not needed anymore.
   - New partials added for groups of `<meta>` elements.

This PR also includes some Schema.org fixes:

1. The site now has a `WebPage` schema type, as root, then contains an `Event`. This introduction was to add context to the `<meta itemprop="">` elements.
1. The speaker pages were using the talk title as the `author`'s name, so I switched it to their `fullName`
1. The `dateModified` attribute only exists for CreativeWorks, and as such doesn't apply to Organizations or WebPages.

Apologies for the text-formatting woes. I can't find out what's causing it. It's already disabled in my VSCode settings. :(

### CODE REVIEW

**Comment by ndorfin** [comment]
Ah, I see the workspace has the following in `.vscode/settings.json`:

```
  …
  "editor.formatOnSave": true,
  …
```

This is overriding my personal settings (set to `false`).
You might want to update this settings file to include the type(s) of HTML formatting you want, or whether to use another formatter such as Prettier.

**Comment by praesongprasit** [comment]
> Ah, I see the workspace has the following in `.vscode/settings.json`:
> 
> ```
>   …
>   "editor.formatOnSave": true,
>   …
> ```
> 
> This is overriding my personal settings (set to `false`). You might want to update this settings file to include the type(s) of HTML formatting you want, or whether to use another formatter such as Prettier.

Ah, we definitely are using Prettier on the codebase. Thanks for figuring this out.

**Review by praesongprasit — CHANGES_REQUESTED** [review]
Ok, sorry this will be a bit painful, but at least it'll be the last really painful one for both of us.

### Eleventy errors

This branch is showing a few eleventy build errors. Could you please check that it's running fine on yours?

### Code formatting issue

I've discovered that Prettier doesn't do Nunjucks files a while back but neglected to do much about it. I didn't expect contribution this early on in our journey :)

Prettier is now the default formatter for the codebase in `.vscode/settings.json`.

As for Nunjucks formatting, I've added Nunjucks Formatter into work space recommendation and settings, then ran all the files through it.

If possible, please rebase the latest version of `main`. (Or would cherry pick be easier?) 
There will be a few conflicts due to reformatted spacing according to Nunjucks formatter rule.

If you're not keen to do this, I'm happy to branch off your branch (after eleventy errors have been fixed), resolve the merge conflict myself, reformat code, close this PR, and commit changes from the new conflict resolved branch.

Really appreciate you doing all this regardless though.

**Comment by ndorfin** [comment]
That's all good Prae, I'm glad there's a way forward.
I'll take a look later today or tomorrow.

**Comment by ndorfin** [comment]
Hi @praesongprasit 
I think I've managed to fix the merge conflicts.

I couldn't reproduce the problems you mentioned you were getting with Eleventy build errors:

```
➜  nztechrally.com git:(issue-9-html-validation-fixes) npm run build

> nztechrally@1.0.0 build
> eleventy

[11ty] Writing dist/browserconfig.xml from ./src/browserconfig.njk
[11ty] Writing dist/sitemap.xml from ./src/sitemap.njk
[11ty] Writing dist/.htaccess from ./src/htaccess.njk
[11ty] Writing dist/404.html from ./src/404.njk
[11ty] Writing dist/about/index.html from ./src/about.njk
[11ty] Writing dist/code-of-conduct/index.html from ./src/code-of-conduct.njk
[11ty] Writing dist/faq/index.html from ./src/faq.njk
[11ty] Writing dist/index.html from ./src/index.njk
[11ty] Writing dist/newsletter-confirmation/index.html from ./src/newsletter-confirmation.njk
[11ty] Writing dist/privacy-policy/index.html from ./src/privacy-policy.njk
[11ty] Writing dist/sales-policy/index.html from ./src/sales-policy.njk
[11ty] Writing dist/schedule/index.html from ./src/schedule.njk
[11ty] Writing dist/speakers-info/index.html from ./src/speakers-info.njk
[11ty] Writing dist/sponsor/index.html from ./src/sponsor.njk
[11ty] Writing dist/volunteer/index.html from ./src/volunteer.njk
[11ty] Writing dist/speakers/katrina-clokie/index.html from ./src/speakers/katrina-clokie.md (njk)
Inclusive Language Linter (./src/speakers/jade-thomas.md):
    y mishap can be enormous; not just financial and reputational, b
     can be crippling.
</p>
<p>
  However, at what point does this lack
[11ty] Writing dist/speakers/jade-thomas/index.html from ./src/speakers/jade-thomas.md (njk)
[11ty] Writing dist/speakers/erica-anderson/index.html from ./src/speakers/erica-anderson.md (njk)
[11ty] Writing dist/speakers/mrinal-mukherjee/index.html from ./src/speakers/mrinal-mukherjee.md (njk)
[11ty] Writing dist/speakers/jenny-sahng/index.html from ./src/speakers/jenny-sahng.md (njk)
[11ty] Writing dist/speakers/aleisha-amohia/index.html from ./src/speakers/aleisha-amohia.md (njk)
[11ty] Writing dist/speakers/allen-geer/index.html from ./src/speakers/allen-geer.md (njk)
Inclusive Language Linter (./src/speakers/adam-howard.md):
    n, and not something that can simply be manufactured and measured.
     lot like culture.</p>
<p>And just as culture is emergent from a
[11ty] Writing dist/speakers/adam-howard/index.html from ./src/speakers/adam-howard.md (njk)
[11ty] Benchmark     37ms  10%    20× (Configuration) "jsmin" Nunjucks Async Filter
[11ty] Copied 68 files / Wrote 23 files in 0.26 seconds (11.3ms each, v2.0.1)
```

I'm running `nodejs v20.2.0`, using ASDF.

**Comment by SteveBarnett** [comment]
Hi hi! Might it be worth splitting this into a few, smaller, PRs? Or would that be more of a headache? 🤔 
I'm thinking something like:

- move stuff to partials
- simplify HTML
- indenting and attribute formatting
- date stuff

**Comment by praesongprasit** [comment]
@SteveBarnett Yup next time we'll definitely want to do smaller PRs. We live and learn!!

**Comment by praesongprasit** [comment]
@ndorfin Thank you very much for resolving all those conflicts. 

I've installed the latest npm so it works now. 

I'll update README to include `nvm install` command at setup and after upgrades

**Comment by ndorfin** [comment]
Thanks @praesongprasit 
Sorry about the PR size, I think I fell down the rabbit hole!

**Pull request merged**
